spring:
  application:
    name: ticketing-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ticketing_db
    username: ${DB_USER:ticket_user}
    password: ${DB_PASSWORD:ticket_password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email@gmail.com} T
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3

application:
  name: ticketing-backend
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}